FROM ubuntu:20.04

# Basic packages
RUN apt-get -y -o Acquire::ForceIPv4=true update
RUN apt-get install -y make scons g++
RUN apt-get install -y wget unzip vim

# Set working directory
RUN mkdir -p /usr/protongraph
WORKDIR /usr/protongraph

# Build binaries + templates for Godot 3.4.2
RUN mkdir -p ~/.local/share/godot/templates/3.4.2.stable
RUN wget https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_linux_headless.64.zip && unzip Godot_v3.4.2-stable_linux_headless.64.zip && mv Godot_v3.4.2-stable_linux_headless.64 godot.linux.3.4.2-stable.headless.64
RUN wget https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_export_templates.tpz && unzip Godot_v3.4.2-stable_export_templates.tpz
RUN cd templates && cp * ~/.local/share/godot/templates/3.4.2.stable && cd -

# Copy source files across
COPY addons /usr/protongraph/addons
COPY common /usr/protongraph/common
COPY config /usr/protongraph/config
COPY core /usr/protongraph/core
COPY mklove /usr/protongraph/mklove
COPY native /usr/protongraph/native
COPY nodes /usr/protongraph/nodes
COPY thirdparty /usr/protongraph/thirdparty
COPY ui /usr/protongraph/ui
COPY export_presets.cfg /usr/protongraph/export_presets.cfg
COPY Makefile /usr/protongraph/Makefile

# Run make commands
RUN mkdir -p /builds/server
RUN make compile_linux SHELL=/bin/bash
RUN make godot_export_linux

# Extract binary from container

RUN echo 'sleep infinity' >> /bootstrap.sh
RUN chmod +x /bootstrap.sh

CMD /bootstrap.sh

# ELF utils
# RUN apt-get -y install binutils elfutils

# RUN echo 'sleep infinity' >> /bootstrap.sh
# RUN chmod +x /bootstrap.sh

# CMD /bootstrap.sh